import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { Check, ChevronLeft } from "lucide-react";
import { AppShell } from "@/components/atelier/AppShell";
import { TopBar } from "@/components/atelier/TopBar";
import { useCart } from "@/components/atelier/CartContext";
import { formatNaira } from "@/data/atelier";

export const Route = createFileRoute("/checkout")({ component: CheckoutPage });
function CheckoutPage() { const { items } = useCart(); const navigate = useNavigate(); const total = items.reduce((sum, item) => sum + item.design.price * item.quantity, 0); return <AppShell><TopBar /><main className="px-4 py-6"><Link to="/cart" className="flex items-center gap-1 text-xs text-muted-foreground"><ChevronLeft className="size-4" /> Back to cart</Link><p className="mt-6 text-[10px] uppercase tracking-[0.2em] text-primary">Almost yours</p><h1 className="mt-1 font-display text-3xl text-foreground">Checkout</h1><div className="mt-5 flex flex-col gap-3 rounded-2xl border border-border bg-card p-4"><h2 className="text-sm font-semibold text-foreground">Delivery details</h2><input required placeholder="Full name" className="rounded-xl border border-border bg-background px-3 py-3 text-xs text-foreground outline-none" /><input required placeholder="Phone number" className="rounded-xl border border-border bg-background px-3 py-3 text-xs text-foreground outline-none" /><input required placeholder="Delivery address" className="rounded-xl border border-border bg-background px-3 py-3 text-xs text-foreground outline-none" /><div className="mt-2 flex justify-between border-t border-border pt-3 text-sm"><span className="text-muted-foreground">Order total</span><strong className="text-foreground">{formatNaira(total)}</strong></div><button type="button" disabled={!items.length} onClick={() => navigate({ to: "/request-received", search: { phone: "08000000000" } })} className="mt-2 flex items-center justify-center gap-2 rounded-full bg-primary py-3.5 text-sm font-semibold text-primary-foreground disabled:opacity-50">Place order <Check className="size-4" /></button></div><p className="mt-4 text-center text-[10px] leading-relaxed text-muted-foreground">This is a simulated checkout. Our team will confirm availability and delivery with you personally.</p></main></AppShell>; }
